version: '3.4'
name: rentflex
networks:
  rentflex:
volumes:
  sqlserver:
  azurite:

services:
  rentflex-web:
    container_name: RentFlex-Web
    image: ${DOCKER_REGISTRY-}rentflexweb
    build:
      context: .
      dockerfile: RentFlex.Web/Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - rentflex-db
    - rentflex-cache
    - rentflex-azurite
    networks:
    - rentflex
    environment:
    - ASPNETCORE_ENVIRONMENT=Staging
    - ASPNETCORE_HTTP_PORTS=8080

  rentflex-db:
    container_name: RentFlex-Db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - "1433:1433"
    environment:
        MSSQL_SA_PASSWORD: Password123!
        ACCEPT_EULA: "Y"
    networks:
    - rentflex
    volumes:
    - sqlserver:/var/opt/mssql
 
  rentflex-cache:
    container_name: Rentflex-Cache
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
    - rentflex

  rentflex-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: RentFlex-Azurite
    ports:
    - "10000:10000"
    volumes:
    - azurite:/data
    hostname: azurite
    networks:
    - rentflex
    