apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: azurite
  name: azurite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
