apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rentflex-web
  name: rentflex-web
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: rentflex-web
