apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rentflex-web
  name: rentflex-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rentflex-web
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: rentflex-web
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          image: rentflexweb
          name: rentflex-web
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
