apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rentflex-azurite
  name: rentflex-azurite
spec:
  type: NodePort
  ports:
    - name: "10000"
      port: 10000
      targetPort: 10000
      nodePort: 30000
  selector:
    io.kompose.service: rentflex-azurite
