apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rentflex-db
  name: rentflex-db
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: rentflex-db
