apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rentflex-azurite
  name: rentflex-azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rentflex-azurite
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s-manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: rentflex-azurite
    spec:
      containers:
        - image: mcr.microsoft.com/azure-storage/azurite
          name: rentflex-azurite
          ports:
            - containerPort: 10000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: azurite
      hostname: rentflex-azurite
      restartPolicy: Always
      volumes:
        - name: azurite
          persistentVolumeClaim:
            claimName: azurite
